name: mips64el-linux-gnu-musl-gcc7.3.0

on:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run docker-compose up
      run: docker-compose up    
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "mips64el-linux-gnu-musl-gcc7.3.0"
        files: output.tar.bz2
